# Manually created as-at 2021-12-01
# Last updated as-at 2022-06-20
name: oreum_recruit_exercises
channels:
- defaults
dependencies:
- ipython==8.3.*
- jupyterlab==3.3.*
- matplotlib==3.5.*
- numpy==1.22.*         # note install here to compile against Intel MKL BLAS
- pandas==1.4.*
- pip==21.2.*
- python==3.9.*
- scipy==1.7.*          # note install here to compile against Intel MKL BLAS
- scikit-learn==1.0.*
- seaborn==0.11.*
- statsmodels=0.13.*
- sqlalchemy==1.4.*
- conda-forge::watermark==2.3.*
